project:
  type: manuscript

manuscript:
  article: paper.qmd

format:
  wp-pdf:
    include-in-header:
      text: |
        \usepackage{amsmath}
        \usepackage{setspace}

filters:
  - pseudocode
  - diagram

diagram:
  cache: false
  engine:
    tikz:
      execpath: pdflatex
      header-includes:
        - '\usetikzlibrary{arrows, shapes}'

execute:
  freeze: false



